server:
  port: 8083

spring:
  application:
    name: notification-service
  profiles:
    active:
      - local
  datasource:
    shard1:
      url: jdbc:postgresql://${project.variables.datasource.url_1}/trade_project
      username: ${project.variables.datasource.username_1}
      password: ${project.variables.datasource.password_1}
    shard2:
      url: jdbc:postgresql://${project.variables.datasource.url_2}/trade_project
      username: ${project.variables.datasource.username_2}
      password: ${project.variables.datasource.password_2}
  flyway:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    notify-subscription-topic: notify-subscription-topic
    trade-subscription-topic: trade-subscription-topic
    trade-order-topic: trade-order-topic
    consumer:
      bootstrap-servers: ${project.variables.kafka.url}
      group-id: notification-group
      auto-offset-reset: earliest
  mail:
    host: ${project.variables.mail.smtp.host}
    port: ${project.variables.mail.port}
    username: ${project.variables.mail.service.user}
    password: ${project.variables.mail.service.password}
    protocol: ${project.variables.mail.protocol}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

telegram:
  username: ${project.variables.telegram.username}
  botToken: ${project.variables.telegram.botToken}

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always


project:
  variables:
    service-url: <?>
    datasource:
      url_1: <?>
      url_2: <?>
      username_1: <?>
      username_2: <?>
      password_1: <?>
      password_2: <?>
    kafka:
      url: <?>
    telegram:
      username: <?>
      botToken: <?>
    mail:
      protocol: <?>
      service:
        user: <?>
        password: <?>
      smtp:
        host: <?>
      port: <?>

