auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 3m
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 1m

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 168h

storage_config:
  tsdb:
    dir: /loki/tsdb
  filesystem:
    directory: /loki/chunks

limits_config:
  max_streams_per_user: 1000
  allow_structured_metadata: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
